apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: akshat1608/backend-app:v3
          # resources:
          #   limits:
          #     memory: "1Gi"
          #     cpu: "1"
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mysql-credentials
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: mysql-credentials
            - name: MYSQL_URL
              value: jdbc:mysql://mysql-service:3306/bookStore

          # command: [ "/bin/sh", "-c", "--" ]
          # args: [ "while true; do sleep 30; done;" ]

          ports:
            - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
spec:
  type: LoadBalancer
  selector:
    app: backend-app
  ports:
    - port: 8082
      targetPort: 8082
